version: '3.9'

services:
  react_native:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    container_name: music-timer
    working_dir: /usr/src/app
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules/
    env_file: .env
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    tty: true